// Generated by gencpp from file edg_data_logger/EnableResponse.msg
// DO NOT EDIT!


#ifndef EDG_DATA_LOGGER_MESSAGE_ENABLERESPONSE_H
#define EDG_DATA_LOGGER_MESSAGE_ENABLERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace edg_data_logger
{
template <class ContainerAllocator>
struct EnableResponse_
{
  typedef EnableResponse_<ContainerAllocator> Type;

  EnableResponse_()
    : OutputFileName()  {
    }
  EnableResponse_(const ContainerAllocator& _alloc)
    : OutputFileName(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _OutputFileName_type;
  _OutputFileName_type OutputFileName;





  typedef boost::shared_ptr< ::edg_data_logger::EnableResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::edg_data_logger::EnableResponse_<ContainerAllocator> const> ConstPtr;

}; // struct EnableResponse_

typedef ::edg_data_logger::EnableResponse_<std::allocator<void> > EnableResponse;

typedef boost::shared_ptr< ::edg_data_logger::EnableResponse > EnableResponsePtr;
typedef boost::shared_ptr< ::edg_data_logger::EnableResponse const> EnableResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::edg_data_logger::EnableResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::edg_data_logger::EnableResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::edg_data_logger::EnableResponse_<ContainerAllocator1> & lhs, const ::edg_data_logger::EnableResponse_<ContainerAllocator2> & rhs)
{
  return lhs.OutputFileName == rhs.OutputFileName;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::edg_data_logger::EnableResponse_<ContainerAllocator1> & lhs, const ::edg_data_logger::EnableResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace edg_data_logger

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::edg_data_logger::EnableResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::edg_data_logger::EnableResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::edg_data_logger::EnableResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::edg_data_logger::EnableResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::edg_data_logger::EnableResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::edg_data_logger::EnableResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::edg_data_logger::EnableResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4cb91e9e55bf61a0d4abe7a49e8f55de";
  }

  static const char* value(const ::edg_data_logger::EnableResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4cb91e9e55bf61a0ULL;
  static const uint64_t static_value2 = 0xd4abe7a49e8f55deULL;
};

template<class ContainerAllocator>
struct DataType< ::edg_data_logger::EnableResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "edg_data_logger/EnableResponse";
  }

  static const char* value(const ::edg_data_logger::EnableResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::edg_data_logger::EnableResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string OutputFileName\n"
"\n"
;
  }

  static const char* value(const ::edg_data_logger::EnableResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::edg_data_logger::EnableResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.OutputFileName);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct EnableResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::edg_data_logger::EnableResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::edg_data_logger::EnableResponse_<ContainerAllocator>& v)
  {
    s << indent << "OutputFileName: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.OutputFileName);
  }
};

} // namespace message_operations
} // namespace ros

#endif // EDG_DATA_LOGGER_MESSAGE_ENABLERESPONSE_H
