// Generated by gencpp from file tae_datalogger/Enable.msg
// DO NOT EDIT!


#ifndef TAE_DATALOGGER_MESSAGE_ENABLE_H
#define TAE_DATALOGGER_MESSAGE_ENABLE_H

#include <ros/service_traits.h>


#include <tae_datalogger/EnableRequest.h>
#include <tae_datalogger/EnableResponse.h>


namespace tae_datalogger
{

struct Enable
{

typedef EnableRequest Request;
typedef EnableResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Enable
} // namespace tae_datalogger


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tae_datalogger::Enable > {
  static const char* value()
  {
    return "f3f19e69803c97782b2fdad054f37b22";
  }

  static const char* value(const ::tae_datalogger::Enable&) { return value(); }
};

template<>
struct DataType< ::tae_datalogger::Enable > {
  static const char* value()
  {
    return "tae_datalogger/Enable";
  }

  static const char* value(const ::tae_datalogger::Enable&) { return value(); }
};


// service_traits::MD5Sum< ::tae_datalogger::EnableRequest> should match
// service_traits::MD5Sum< ::tae_datalogger::Enable >
template<>
struct MD5Sum< ::tae_datalogger::EnableRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tae_datalogger::Enable >::value();
  }
  static const char* value(const ::tae_datalogger::EnableRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tae_datalogger::EnableRequest> should match
// service_traits::DataType< ::tae_datalogger::Enable >
template<>
struct DataType< ::tae_datalogger::EnableRequest>
{
  static const char* value()
  {
    return DataType< ::tae_datalogger::Enable >::value();
  }
  static const char* value(const ::tae_datalogger::EnableRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tae_datalogger::EnableResponse> should match
// service_traits::MD5Sum< ::tae_datalogger::Enable >
template<>
struct MD5Sum< ::tae_datalogger::EnableResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tae_datalogger::Enable >::value();
  }
  static const char* value(const ::tae_datalogger::EnableResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tae_datalogger::EnableResponse> should match
// service_traits::DataType< ::tae_datalogger::Enable >
template<>
struct DataType< ::tae_datalogger::EnableResponse>
{
  static const char* value()
  {
    return DataType< ::tae_datalogger::Enable >::value();
  }
  static const char* value(const ::tae_datalogger::EnableResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TAE_DATALOGGER_MESSAGE_ENABLE_H
